sudo: false
language: python
python:
  - "2.7"
env:
  - PIP_DOWNLOAD_CACHE="pip_cache"
cache:
  directories:
    - pip_cache
install:
  - pip install -r requirements.txt
script: python check_advisories.py --all
notifications:
  irc:
    channels:
      - "irc.mozilla.org#www"
    on_success: never
    on_failure: always
    use_notice: true
